---
name: DOH Proxy
title: DOH Proxy
description: A DNS-over-HTTPS Proxy
repository: facebookexperimental/doh-proxy
theme: jekyll-theme-slate
timezone: America/Los_Angeles
sass:
  style: compressed
markdown: kramdown

plugins:
  - jekyll-relative-links

relative_links:
  enabled:     true
  collections: false

